# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'kubedeploy'
    namespace: 'default'
    manifests: |
      manifests/deployment.yml
      manifests/service.yml
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- task: DownloadSecureFile@1
  name: kubeconfig
  inputs:
    secureFile: 'config'
- task: CmdLine@2
  inputs:
    script: |
      mv $(kubeconfig.secureFilePath) /home/vsts/.kube/
      ls -a /home/vsts/.kube/
      kubectl get svc -n default juiceshopv1 -o json > /home/vsts/svc.json
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      #! /usr/bin/python3
      
      import json
      import os
      
      with open("/home/vsts/svc.json", "r") as f:
          kubeoutput = f.read()
          kubeoutput_dict = json.loads(kubeoutput)
          f.close()
      svc_ip = kubeoutput_dict['status']['loadBalancer']['ingress'][0]
      with open("/home/vsts/svc_ip", "w",encoding = 'utf-8') as f:
          print(svc_ip)
          f.write(json.dumps(svc_ip))
          f.close()
      os.system("cat /home/vsts/svc_ip")
- task: CmdLine@2
  inputs:
    script: |
      wget https://raw.githubusercontent.com/aravindan-acct/cudawaasdemo2022/main/scripts/waas_configuration_updated.py
      sudo apt install python3-pip
      wget https://raw.githubusercontent.com/aravindan-acct/cudawaasdemo2022/main/scripts/requirements.txt
      sudo pip3 install -r requirements.txt
      python3 waas_configuration_updated.py
