# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'kubedeploy'
    namespace: 'default'
    manifests: |
      manifests/deployment.yml
      manifests/service.yml
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kubedeploy'
    namespace: 'default'
    command: 'get'
    arguments: 'svc juiceshopv1 > svc.json'